// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd2izvPiCOqFEnFaSZZAEANnnx1CihGNw',
    appId: '1:564887217389:web:0b05d6ef39a291380018e4',
    messagingSenderId: '564887217389',
    databaseURL: 'https://fypposting-c6158-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'fypposting-c6158',
    authDomain: 'fypposting-c6158.firebaseapp.com',
    storageBucket: 'fypposting-c6158.appspot.com',
    measurementId: 'G-5JJNRP0HJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYmrrMMpo13VLnjwimSYDFKWokcximazw',
    appId: '1:564887217389:android:739c20997c577c4c0018e4',
    databaseURL: 'https://fypposting-c6158-default-rtdb.asia-southeast1.firebasedatabase.app',
    messagingSenderId: '564887217389',
    projectId: 'fypposting-c6158',
    storageBucket: 'fypposting-c6158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtA_K0K1B58_09CHGciBOsocfvfo8A2I',
    appId: '1:564887217389:ios:72281a801889400f0018e4',
    databaseURL: 'https://fypposting-c6158-default-rtdb.asia-southeast1.firebasedatabase.app',
    messagingSenderId: '564887217389',
    projectId: 'fypposting-c6158',
    storageBucket: 'fypposting-c6158.appspot.com',
    iosBundleId: 'com.example.tourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTtA_K0K1B58_09CHGciBOsocfvfo8A2I',
    appId: '1:564887217389:ios:97e0cf7087c858e70018e4',
    messagingSenderId: '564887217389',
    projectId: 'fypposting-c6158',
    storageBucket: 'fypposting-c6158.appspot.com',
    iosBundleId: 'com.example.tourism.RunnerTests',
  );
}
